services:
  api:
    build: .
    container_name: crudfastapi_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build: .
    container_name: crudfastapi_worker
    command: python -m worker.processor
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: crudfastapi_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: crudfastapi_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
